import{S as u,i as n}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const p=document.querySelector(".gallery");let m=new u(".gallery a",{captionsData:"alt",captionDelay:250});function d(l){const{webformatURL:t,largeImageURL:r,tags:a,likes:e,views:s,comments:o,downloads:c}=l;return`<li class="item"> <a class="gallery-item" href="${r}">
                            <img class="gallery-image"
                            src="${t}"
                            alt="${a}"/>
                        </a>
                        <ul class="descr">
                        <li class="descr-item"><p class="descr-title">Likes<span class="descr-value">${e}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Views<span class="descr-value"> ${s}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Comments<span class="descr-value"> ${o}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Downloads<span class="descr-value"> ${c}</span></p></li>
                        </ul>
                        </li>`}function f(l){const t=l.hits.map(r=>d(r)).join("");p.innerHTML=t,m.refresh()}function y(l){const t={key:"42343629-db0a88f68e5938b107ae69266",q:`${l.trim()}`.split(" ").map(a=>a.toLowerCase().trim()).join("+"),image_type:"photo",orientation:"horizontal",safesearch:!0},r=`https://pixabay.com/api/?key=${t.key}&q=${t.q}&image-type=${t.image_type}&orientation=${t.orientation}&safesearch=${t.safesearch}`;return fetch(r).then(a=>{if(!a.ok)throw new Error(a.status);return a.json()}).catch(a=>{console.log(a)})}const g=document.querySelector(".form"),h=document.querySelector(".gallery"),i=document.querySelector(".loader");i.style.display="none";g.addEventListener("submit",l=>{l.preventDefault(),h.innerHTML="";const t=l.target.elements.input.value.trim();if(t===""){n.warning({message:"Please enter a valid request!",position:"topRight"});return}i.style.display="block",y(t).then(r=>{r.hits.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):f(r)}).catch(r=>{console.log(r)}).finally(()=>{i.style.display="none"}),l.target.reset()});
//# sourceMappingURL=commonHelpers.js.map
