import{i as p,S as d}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const n=document.querySelector(".form"),c=document.querySelector(".gallery"),o=document.querySelector(".loader");o.style.display="none";n.addEventListener("submit",l=>{l.preventDefault();const t=l.target.elements.input.value;u(t),n.reset()});function u(l){const t={key:"42343629-db0a88f68e5938b107ae69266",q:`${l.trim()}`.split(" ").map(r=>r.toLowerCase().trim()).join("+"),image_type:"photo",orientation:"horizontal",safesearch:!0},i=`https://pixabay.com/api/?key=${t.key}&q=${t.q}&image-type=${t.image_type}&orientation=${t.orientation}&safesearch=${t.safesearch}`;return o.style.display="block",fetch(i).then(r=>r.json()).then(r=>{if(r.hits.length===0)o.style.display="none",c.innerHTML="",p.error({message:"Sorry, there are no images matching your search query. Please try again!"});else{o.style.display="none";const s=r.hits.map(a=>`<li class="item"> <a class="gallery-item" href="${a.largeImageURL}">
                            <img class="gallery-image"
                            src="${a.webformatURL}"
                            alt="${a.tags}"/>
                        </a>
                        <ul class="descr">
                        <li class="descr-item"><p class="descr-title">Likes<span class="descr-value">${a.likes}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Views<span class="descr-value"> ${a.views}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Comments<span class="descr-value"> ${a.comments}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Downloads<span class="descr-value"> ${a.downloads}</span></p></li>
                        </ul>
                        </li>`).join("");c.innerHTML=s}new d(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}).catch(r=>{console.log(r)})}
//# sourceMappingURL=commonHelpers.js.map
