import{S as u,i as l}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&s(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const p=document.querySelector(".gallery");let m=new u(".gallery a",{captionsData:"alt",captionDelay:250});function d(i){const{webformatURL:t,largeImageURL:a,tags:s,likes:e,views:r,comments:o,downloads:c}=i;return`<li class="item"> <a class="gallery-item" href="${a}">
                            <img class="gallery-image"
                            src="${t}"
                            alt="${s}"/>
                        </a>
                        <ul class="descr">
                        <li class="descr-item"><p class="descr-title">Likes<span class="descr-value">${e}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Views<span class="descr-value"> ${r}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Comments<span class="descr-value"> ${o}</span></p></li>
                        <li class="descr-item"><p class="descr-title">Downloads<span class="descr-value"> ${c}</span></p></li>
                        </ul>
                        </li>`}function f(i){const t=i.hits.map(a=>d(a)).join("");p.innerHTML=t,m.refresh()}function g(i){const t={key:"42343629-db0a88f68e5938b107ae69266",q:`${i.trim()}`.split(" ").map(s=>s.toLowerCase().trim()).join("+"),image_type:"photo",orientation:"horizontal",safesearch:!0},a=`https://pixabay.com/api/?key=${t.key}&q=${t.q}&image-type=${t.image_type}&orientation=${t.orientation}&safesearch=${t.safesearch}`;return fetch(a).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()}).catch(s=>{console.log(s)})}const y=document.querySelector(".form"),h=document.querySelector(".gallery"),n=document.querySelector(".loader");n.style.display="none";y.addEventListener("submit",i=>{i.preventDefault(),h.innerHTML="";const t=i.target.elements.input.value.trim();if(t===""){l.warning({message:"Please enter a valid request!",position:"topRight"});return}n.style.display="block",g(t).then(a=>{a.hits.length===0?l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):f(a)}).catch(a=>{l.error({message:"Unable to get images",position:"topRight"})}).finally(()=>{n.style.display="none"}),i.target.reset()});
//# sourceMappingURL=commonHelpers.js.map
